apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-helm-chart.fullname" . }}
  labels:
    {{- include "springboot-helm-chart.labels" . | nindent 4 }}
data:
    {{- range $key, $value := .Values.properties }}
    {{ $key | replace "." "_" | replace "-" "" | upper }}: {{ $value | quote}}
    {{- end }}
